name: Install mitmproxy and certificate
description: Install mitmproxy and the CA certificate it generates

runs:
  using: composite
  steps:
    - name: Install mitmproxy
      shell: bash
      run: pipx install mitmproxy
    - name: Make mitmdump generate certificates
      shell: bash
      run: mitmdump -s ${{ github.action_path }}/init_cert.py
    - name: Install CA certificate to system
      shell: bash
      run: |
        openssl x509 -in "$HOME/.mitmproxy/mitmproxy-ca-cert.pem" -inform PEM -out cert.crt
        sudo cp cert.crt /usr/local/share/ca-certificates/
        sudo update-ca-certificates
