[package]
name = "autobib"
authors = ["Alex Rutar <alex@rutar.org>", "Peiran Wu"]
description = "An automatic bibliography generation tool."
homepage = "https://github.com/wupr/autobib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
log = { version = "0.4", features = ["release_max_level_info"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
clap-verbosity-flag = "2.2"
crossterm = "0.28"
delegate = "0.12"
directories = "5.0"
edit = "0.1"
either = "1.13"
itertools = "0.13"
lazy_static = "1.5"
memchr = "2.7"
nonempty = "0.10"
nucleo-picker = "0.4"
quick-xml = { version = "0.31", features = ["serialize"] }
regex = "1.10"
reqwest = { version = "0.12", features = ["rustls-tls", "blocking", "gzip"] }
rusqlite = { version = "0.31", features = ["bundled", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_bibtex = "0.3.1"
stderrlog = "0.6"
thiserror = "1.0"
