[package]
name = "autobib"
authors = ["Alex Rutar <alex@rutar.org>", "Peiran Wu"]
description = "An automatic bibliography generation tool."
version = "0.1.0"
edition = "2021"

[dependencies]
biblatex = { version = "0.9", features = ["serde"] }
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.4"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
rusqlite = { version = "0.30", features = ["bundled", "chrono"] }
