[package]
name = "autobib"
authors = ["Alex Rutar <alex@rutar.org>", "Peiran Wu"]
description = "An automatic bibliography generation tool."
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.4", features = ["derive"] }
itertools = "0.12"
quick-xml = { version = "0.31", features = ["serialize"] }
regex = "1.10"
reqwest = { version = "0.11", features = ["rustls-tls", "blocking", "gzip"] }
rusqlite = { version = "0.30", features = ["bundled", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde-aux = "4.4" 
serde_bibtex = "0.1.0"
serde_json = "1.0"
serde_with = "3.4"
xdg = "2.5"
