# Preferred providers for various operations:
# - the printed key when selecting an option with `autobib find`
# - the provider used to attempt remote resolution of imported bibtex entries
preferred_providers = []

# Actions related to the picker interface, for example when running `autobib find`
[picker]

# Whether or not to ignore hidden files and directories in the attachment directories.
# Note that if `true` will skip non-hidden files inside hidden directories.
ignore_hidden_files = false

# Actions to perform when adding a new item to the database from a remote provider.
# These actions are not run for local operations, such as `autobib local`.
[on_insert]

# Whether or not to normalize whitespace, which means deleting leading and trailing
# whitespace and converting any consecutive blocks of unescaped whitespace (such as
# normal spaces, or newlines, or Unicode whitespace) into a single ASCII space.
normalize_whitespace = false

# A list of BibTeX fields from which to automatically set the `eprint` and
# `eprinttype` fields. For example, if `set_eprint = ["doi"]`, then any new entry
# which contains `doi = {...}` will receive new fields `eprint = {...}` and
# `eprinttype = {doi}`, overwriting existing values of `eprint` and `eprinttype`.
set_eprint = []

# Whether or not to strip trailing numbered series indicators, such as the (2) in
# "Ann. Math. (2)"
strip_journal_series = false

# Automatically convert aliases to provider:sub_id pairs, based on regex match rules.
[alias_transform]

# A list of [pattern, provider] pairs. Each matching pattern must have exactly one
# capture group. The matching capture group matches is used to create a corresponding
# citation key of the form `provider:captured`. You can validate your configuration with
# `autobib util check`.
#
# The regex syntax is documented at https://docs.rs/regex/latest/regex/#syntax
# 
# Here are some suggested capture groups for various identifiers.
# 
# - arxiv (new style only): ([0-9][0-9](?:0[1-9]|1[0-2])[.][0-9]{4,5})
# - doi: (10.\d{4,9}/[-._;()/:a-zA-Z0-9]+)|(10.1002/[^\s]+)
# - isbn: ([0-9]{10}(?:[0-9]{3})
# - jfm: ([0-9]{2}\.[0-9]{4}\.[0-9]{2})
# - mr: ([0-9]{7})
# - ol: ([0-9]{8}M)
# - zbl: ([0-9]{4}\.[0-9]{5})
# - zbmath: ([0-9]{8})
#
# For example, to automatically transform 'zbMATH'-style aliases of the form
# 'zbMATH06346461', one would set
#
# rules = [["^zbMATH([0-9]{8})$", "zbmath"]]
rules = []

# Whether or not to automatically create new permanent aliases in the database from
# matched aliases.
create_alias = false
