name: CI
description: Run Rust tests and checks

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  RUST_BACKTRACE: 1

  REMOTES_FILE: tests/remotes.txt
  CACHE_FORMAT_DEF: src/http/cache/format.rs
  AUTOBIB_RESPONSE_CACHE_PATH: responses.dat
  CACHE_PREFIX: responses

jobs:
  tests:
    strategy:
      matrix:
        image: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.image }}
    steps:
    # Windows configuration; this has to run before checkout!
    - name: Configure Git on Windows
      if: runner.os == 'Windows'
      run: git config --global core.autocrlf false

    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    # Load/create HTTP response cache
    - name: Set up response data cache
      id: response-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.AUTOBIB_RESPONSE_CACHE_PATH }}
        key: ${{ env.CACHE_PREFIX }}-${{ matrix.image }}-${{ hashFiles(env.REMOTES_FILE, env.CACHE_FORMAT_DEF) }}
    - name: Build response cache binary
      if: steps.response-cache.outputs.cache-hit != 'true'
      run: cargo build --locked --features write_response_cache
    - name: Create response cache
      if: steps.response-cache.outputs.cache-hit != 'true'
      run: cat '${{ env.REMOTES_FILE }}' | xargs -- cargo run --locked --features write_response_cache -- -vv get --retrieve-only --ignore-null

    # Actually run tests
    - name: Build test binaries
      run: cargo test --no-run --locked --features read_response_cache
    - name: Run tests
      run: cargo test --no-fail-fast --locked --features read_response_cache

  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2

    # Rust doc/fmt/clippy
    - name: Build docs
      run: cargo doc --no-deps --locked
    - name: Run Clippy lints
      run: cargo clippy --locked
    - name: Check formatting
      run: cargo fmt --check

    # Check remotes file formatting
    - name: Check remotes file is sorted
      shell: bash
      run: sort -C ${{ env.REMOTES_FILE }}
    - name: Check remotes file contains no duplicates
      shell: bash
      run: test "$(cat ${{ env.REMOTES_FILE }} | uniq -d | wc -w)" -eq 0
