name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

concurrency:
  group: release
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: -D warnings
  RUST_BACKTRACE: 1
  RUST_VERSION: ${{ vars.RUST_VERSION }}
  RELEASE_TAG: ${{ github.ref_name }}
  RELEASE_BRANCH: main
  CRATE: autobib
  BIN: autobib

jobs:
  verify:
    name: Verify release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # required for verifying the tag lives on origin/$RELEASE_BRANCH
          persist-credentials: false

      - name: Get the release version from the tag
        id: release
        shell: bash
        run: |
          version="${RELEASE_TAG:1}"
          echo "VERSION=$version" >> "$GITHUB_ENV"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Check that the tag is on main
        shell: bash
        run: |
          set -euxo pipefail

          git merge-base --is-ancestor "$RELEASE_TAG^{}" "origin/$RELEASE_BRANCH"

      - name: Show the version
        run: |
          echo "version is: $VERSION"

      - name: Check that tag version and Cargo.toml version are the same
        shell: bash
        run: |
          PACKAGE_VERSION="$(
            cargo metadata --no-deps --format-version 1 |
              jq -r --arg crate "$CRATE" \
                '.packages[] | select(.name == $crate) | .version'
          )"

          if [[ "$PACKAGE_VERSION" != "$VERSION" ]]; then
            echo >&2 "version does not match Cargo.toml"
            exit 1
          fi

      - name: Check that a changelog file with the correct name exists
        id: changelog
        shell: bash
        run: |
          CHANGELOG_FILE="docs/changelog/$RELEASE_TAG.md"
          if [[ ! -f "$CHANGELOG_FILE" ]]; then
            echo >&2 "Changelog file not found!"
            exit 1
          fi
          echo "CHANGELOG_FILE=$CHANGELOG_FILE" >> "$GITHUB_ENV"
          echo "changelog_file=$CHANGELOG_FILE" >> "$GITHUB_OUTPUT"

      - name: Show the changelog file
        run: |
          echo "changelog file is: $CHANGELOG_FILE"

    outputs:
      version: ${{ steps.release.outputs.version }}
      changelog_file: ${{ steps.changelog.outputs.changelog_file }}

  generate-licenses:
    needs: verify
    uses: ./.github/workflows/cargo-about.yml

  build:
    name: Compile release binaries
    needs: [verify, generate-licenses]
    runs-on: ${{ matrix.image }}
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - image: ubuntu-24.04
            target: x86_64-unknown-linux-musl
          - image: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - image: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
          - image: macos-26
            target: aarch64-apple-darwin
          - image: macos-26-intel
            target: x86_64-apple-darwin
          - image: windows-2025
            target: x86_64-pc-windows-gnu
          - image: windows-2025
            target: x86_64-pc-windows-msvc
          - image: windows-11-arm
            target: aarch64-pc-windows-msvc

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # make sure this contains the toolchain version!
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.target }}

      - name: Install build deps (Linux musl)
        if: endsWith( matrix.target, '-unknown-linux-musl' )
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Download licenses file artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: cargo-about-licenses-html

      - name: Build and package
        shell: bash
        env:
          TARGET: ${{ matrix.target }}
          VERSION: ${{ needs.verify.outputs.version }}
        run: |
          set -euxo pipefail

          # build release binary
          cargo build --verbose --release --locked \
            --package "$CRATE" --bin "$BIN" \
            --config 'target."cfg(all())".rustflags = ["-D", "warnings"]' \
            --target "$TARGET"

          # some naming setup
          suffix=""
          if [[ "$RUNNER_OS" == Windows ]]; then
            suffix=".exe"
          fi

          # target dirs:
          # - archive is the directory that will be zipped for this target
          # - dist/ is where things are copied at the end
          archive="$BIN-$VERSION-$TARGET"
          mkdir "$archive" dist

          # check that the binary runs and copy it to the archive
          compiled="target/$TARGET/release/$BIN$suffix"
          "$compiled" --version
          cp "$compiled" "$archive"/

          # copy documentation files
          cp {README.md,COPYRIGHT,LICENSE,third-party-licenses.html} "$archive"/
          cp "docs/changelog/$RELEASE_TAG.md" "$archive"/CHANGELOG.md

          # create compressed archives and hashes
          if [[ "$RUNNER_OS" == Windows ]]; then
            7z a dist/"$archive.zip" "$archive"
          else
            tar czf dist/"$archive.tar.gz" "$archive"
          fi

      - name: Preserve build archive
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: release-${{ matrix.target }}
          path: dist/*
          if-no-files-found: error

  publish-crates-io:
    name: Publish release to crates.io
    needs: [verify, generate-licenses, build]
    runs-on: ubuntu-latest
    environment: crates.io
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: rust-lang/crates-io-auth-action@c6f97d42243bad5fab37ca0427f495c86d5b1a18 # v1.0.5
        id: auth
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # make sure this contains the toolchain version!
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Publish release
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  publish-github-release:
    name: Publish GitHub release
    needs: [verify, generate-licenses, build, publish-crates-io]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Download release assets
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: release-*
          path: dist
          merge-multiple: true

      - name: Create unified checksum file
        run: |
          set -euxo pipefail

          cd dist
          sha256sum * > SHA256SUMS

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          VERSION: ${{ needs.verify.outputs.version }}
          CHANGELOG_FILE: ${{ needs.verify.outputs.changelog_file }}
        run: |
          set -euxo pipefail

          tail -n +2 "$CHANGELOG_FILE" > "$RUNNER_TEMP/release-notes.md"

          gh release create "$RELEASE_TAG" dist/* \
            --prerelease \
            --verify-tag \
            --title "Autobib $VERSION" \
            --repo "$REPO" \
            --notes-file "$RUNNER_TEMP/release-notes.md"
