name: Prepare network cache

on:
  workflow_call:
    inputs:
      runner_image:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      runner_image:
        required: true
        type: string

permissions:
  contents: read

env:
  REMOTES_FILE: tests/remotes.txt
  AUTOBIB_RESPONSE_CACHE_FILE: responses.dat
  CACHE_PREFIX: responses

jobs:
  lookup:
    name: Look up cache
    runs-on: ${{ inputs.runner_image }}
    outputs:
      cache-hit: ${{ steps.response-cache-restore.outputs.cache-hit }}
    steps:
    - name: Configure Git on Windows
      if: runner.os == 'Windows'
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v5
      with:
        sparse-checkout: |
          ${{ env.REMOTES_FILE }}
    - uses: actions/cache/restore@v4
      id: response-cache-restore
      with:
        path: ${{ env.AUTOBIB_RESPONSE_CACHE_FILE }}
        key: ${{ env.CACHE_PREFIX }}-${{ inputs.runner_image }}-${{ hashFiles(env.REMOTES_FILE) }}
        lookup-only: true

  generate:
    name: Generate
    runs-on: ${{ inputs.runner_image }}
    needs: lookup
    if: needs.lookup.outputs.cache-hit != 'true'
    steps:
    - name: Configure Git on Windows
      if: runner.os == 'Windows'
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Check sorted
      shell: bash
      run: sort -C ${{ env.REMOTES_FILE }}
    - name: Check no duplicates
      shell: bash
      run: test "$(cat ${{ env.REMOTES_FILE }} | uniq -d | wc -w)" -eq 0
    - run: cargo build --features write_response_cache
    - name: Generate response cache
      shell: bash
      run: cat '${{ env.REMOTES_FILE }}' | xargs -- cargo run --features write_response_cache -- -vv get --retrieve-only --ignore-null
    - name: Save response cache
      uses: actions/cache/save@v4
      with:
        path: ${{ env.AUTOBIB_RESPONSE_CACHE_FILE }}
        key: ${{ env.CACHE_PREFIX }}-${{ inputs.runner_image }}-${{ hashFiles(env.REMOTES_FILE) }}
