name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

  REMOTES_FILE: tests/remotes.txt
  FLOWS_FILE: mitmproxy/flows

jobs:
  mitmproxy-flows:
    name: Prepare mitmproxy flows
    uses: ./.github/workflows/mitmdump.yml

  tests:
    runs-on: ubuntu-latest
    needs: mitmproxy-flows
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Get cached mitmproxy flows
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.FLOWS_FILE }}
        key: ${{ runner.os }}-mitmproxy-${{ hashFiles(env.REMOTES_FILE) }}
    - name: Install mitmproxy
      uses: ./.github/actions/install-mitmproxy
    - name: Start mitmdump
      run: mitmdump --server-replay ${{ env.FLOWS_FILE }} --server-replay-reuse --set connection_strategy=lazy &
    - name: Build test binaries
      run: cargo test --no-run --locked
    - name: Run tests
      env:
        ALL_PROXY: http://127.0.0.1:8080
      run: cargo test --no-fail-fast --locked

  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Build docs
      run: cargo doc --no-deps --locked
    - name: Run Clippy lints
      run: cargo clippy --locked
    - name: Check formatting
      run: cargo fmt --check
