name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  mitmproxy-flows:
    uses: ./.github/workflows/mitmdump.yml

  tests:
    runs-on: ubuntu-latest
    needs: mitmproxy-flows
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Get mitmproxy flows cache
      uses: actions/cache/restore@v4
      with:
        path: mitmproxy/flows
        key: ${{ runner.os }}-mitmproxy-${{ hashFiles('mitmproxy/flows') }}
    - name: Initialize mitmproxy
      run: |
        pipx install mitmproxy
        mitmdump --server-replay mitmproxy/flows --server-replay-reuse --set connection_strategy=lazy &
    - name: Build test binaries
      run: cargo test --no-run --locked
    - name: Run tests
      run: cargo test --no-fail-fast --locked


  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Build docs
      run: cargo doc --no-deps --locked
    - name: Run Clippy lints
      run: cargo clippy --locked
    - name: Check formatting
      run: cargo fmt --check
